from fastapi import Depends
from core.repositories.elasticseaerch_repository import ElasticsearchRepository
from services.elasticsearch_service import ElasticsearchService
from factories.services.elasticsearch_client_factory import get_elasticsearch_client

def get_elasticsearch_repository(es_service: ElasticsearchService = Depends(get_elasticsearch_client)):
    return ElasticsearchRepository(elasticsearch_service=es_service)
